server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation

openai:
  api:
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    key: ${OPENAI_API_KEY}

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html